version: "3.9"

services:
  ### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
        # - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        # - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./logs/nginx:/var/log/nginx
      # - ./sites:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      # - "${VARNISH_BACKEND_PORT}:81"
      # depends_on:
      #   - php-fpm
      # networks:
      #   - frontend
      #   - backend
